### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException

### ISSUE THREAD

**Issue by narnacle** [itzg/docker-bungeecord#111]
I don't know when this project was last updated but when I use the docker-compose template in the examples for both Bungeecord and Waterfall I get the following error in the logs:

[23:11:42 ERROR]: Exception in thread "main" java.lang.RuntimeException: Could not load configuration!
[23:11:42 ERROR]: at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:96)
[23:11:42 ERROR]: at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:67)
[23:11:42 ERROR]: at net.md_5.bungee.conf.Configuration.load(Configuration.java:78)
[23:11:42 ERROR]: at io.github.waterfallmc.waterfall.conf.WaterfallConfiguration.load(WaterfallConfiguration.java:67)
[23:11:42 ERROR]: at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
[23:11:42 ERROR]: at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[23:11:42 ERROR]: at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[23:11:42 ERROR]: Caused by: java.io.FileNotFoundException: config.yml (Is a directory)
[23:11:42 ERROR]: at java.base/java.io.FileInputStream.open0(Native Method)
[23:11:42 ERROR]: at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
[23:11:42 ERROR]: at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[23:11:42 ERROR]: at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:76)
[23:11:42 ERROR]: ... 6 more

**Comment by MadLad989** [comment]
Hi, I am also experiencing this issue - the server itself launches with no issues, but the proxy fails to generate a config file, claiming that config.yml is a directory. Using the latest versions of docker compose and all itzg images. Using example docker compose.

docker compose up
[+] Running 3/0
 ✔ Network minecraft2_default    Created                                                                                                                                                                                                                            0.0s 
 ✔ Container minecraft2-mc-1     Created                                                                                                                                                                                                                            0.0s 
 ✔ Container minecraft2-proxy-1  Created                                                                                                                                                                                                                            0.0s 
Attaching to mc-1, proxy-1
mc-1     | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-x--- 7 1000 1000 4096 Aug 19 21:18 /data'
mc-1     | [init] Resolving type given VANILLA
proxy-1  | [init] Resolving type given BUNGEECORD
mc-1     | [init] Resolved version given LATEST into 1.21.1
proxy-1  | [init] Copying configs over...
mc-1     | [mc-image-helper] 21:36:07.902 INFO  : Created/updated 1 property in /data/server.properties
mc-1     | [init] Setting initial memory to 1G and max to 1G
mc-1     | [init] Starting the Minecraft server...
proxy-1  | [init] Replacing env variables in configs that match the prefix CFG_...
mc-1     | Starting net.minecraft.server.Main
proxy-1  | [init] Setting initial memory to 512m and max to 512m
21:36:09 [INFO] Using mbed TLS based native cipher.
21:36:09 [INFO] Using zlib based native compressor.
21:36:09 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.21-R0.1-SNAPSHOT:cd56fb3:1858
21:36:09 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
21:36:09 [INFO] Epoll is working, utilising it!
21:36:09 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
21:36:09 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
21:36:09 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
21:36:09 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
21:36:09 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
21:36:09 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
21:36:09 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.21-R0.1-SNAPSHOT:cd56fb3:1858 by SpigotMC
21:36:09 [INFO] Loaded plugin cmd_find version git:cmd_find:1.21-R0.1-SNAPSHOT:cd56fb3:1858 by SpigotMC
21:36:09 [INFO] Loaded plugin cmd_server version git:cmd_server:1.21-R0.1-SNAPSHOT:cd56fb3:1858 by SpigotMC
21:36:09 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.21-R0.1-SNAPSHOT:cd56fb3:1858 by SpigotMC
21:36:09 [INFO] Loaded plugin cmd_send version git:cmd_send:1.21-R0.1-SNAPSHOT:cd56fb3:1858 by SpigotMC
21:36:09 [INFO] Loaded plugin cmd_list version git:cmd_list:1.21-R0.1-SNAPSHOT:cd56fb3:1858 by SpigotMC
21:36:09 [SEVERE] Exception in thread "main" 
21:36:09 [SEVERE] java.lang.RuntimeException: Could not load configuration!
proxy-1  | 
21:36:09 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:86)
proxy-1  | 
21:36:09 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:76)
proxy-1  | 
21:36:09 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
proxy-1  | 
21:36:09 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
proxy-1  | 
21:36:09 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
proxy-1  | 
21:36:09 [SEVERE] Caused by: java.io.FileNotFoundException: config.yml (Is a directory)
proxy-1  | 
21:36:09 [SEVERE]     at java.base/java.io.FileInputStream.open0(Native Method)
proxy-1  | 
21:36:09 [SEVERE]     at java.base/java.io.FileInputStream.open(Unknown Source)
proxy-1  | 
21:36:09 [SEVERE]     at java.base/java.io.FileInputStream.<init>(Unknown Source)
proxy-1  | 
21:36:09 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:66)
proxy-1  | 
21:36:09 [SEVERE]     ... 4 more
proxy-1  | 
mc-1     | [21:36:13] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
mc-1     | [21:36:15] [ServerMain/INFO]: Loaded 1290 recipes
mc-1     | [21:36:15] [ServerMain/INFO]: Loaded 1399 advancements
mc-1     | [21:36:15] [Server thread/INFO]: Starting minecraft server version 1.21.1
mc-1     | [21:36:15] [Server thread/INFO]: Loading properties
mc-1     | [21:36:15] [Server thread/INFO]: Default game type: SURVIVAL
mc-1     | [21:36:15] [Server thread/INFO]: Generating keypair
mc-1     | [21:36:16] [Server thread/INFO]: Starting Minecraft server on *:25565
mc-1     | [21:36:16] [Server thread/INFO]: Using epoll channel type
mc-1     | [21:36:16] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
mc-1     | [21:36:16] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
mc-1     | [21:36:16] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
mc-1     | [21:36:16] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
mc-1     | [21:36:16] [Server thread/INFO]: Preparing level "world"
mc-1     | [21:36:17] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
mc-1     | [21:36:18] [Worker-Main-7/INFO]: Preparing spawn area: 0%
mc-1     | [21:36:18] [Server thread/INFO]: Time elapsed: 402 ms
mc-1     | [21:36:18] [Server thread/INFO]: Done (2.022s)! For help, type "help"
mc-1     | [21:36:18] [Server thread/INFO]: Starting remote control listener
mc-1     | [21:36:18] [Server thread/INFO]: Thread RCON Listener started
mc-1     | [21:36:18] [Server thread/INFO]: RCON running on 0.0.0.0:25575

**Comment by itzg** [comment]
I'm now thinking in both cases you all accidentally mounted a config file that didn't exist, docker created a placeholder directory for the absent source, and then of course bungeecord, etc will fail to load the directory as if it's a file.

**Comment by MadLad989** [comment]
update on this, I was able to resolve my issue using one of the example compose / config setups. Might be an issue with the main compose template / miscommunication with how it is to be used.
