### ISSUE TITLE
Docker image inconsistency

### ISSUE THREAD

**Issue by weihao** [itzg/docker-bungeecord#58]
Why is bungeecord using `FROM adoptopenjdk:11-jre-hotspot` and server using `adoptopenjdk/openjdk11:alpine-jre`?

**Comment by itzg** [comment]
Is it causing a problem?

Historically I went with Alpine on the Minecraft server image to reduce image size. Over time that benefit has diminished. It also complicates the ability to maintain multi-architecture image builds. I have since ended up with a mixture of Alpine and Ubuntu base images across branches. 

So, on the bungee image I went with the official adoptopenjdk base images to gain multi-architecture support and simplify my maintenance burden across branches.

**Comment by weihao** [comment]
Thanks for the explanation. It is not currently causing any problem, but it is one extra variant that a developer needs to check.

**Comment by itzg** [comment]
> it is one extra variant that a developer needs to check

I'm curious why that matters since the point of containers is abstract away the behavior within the container. Especially in this case it's two packaging types of the same Java version from the same vendor. 

In any case, you can always pair up with the `multiarch` branch/image-tag since it is also based on the same as what I'm using in the bungeecord images:

https://github.com/itzg/docker-minecraft-server/blob/multiarch/Dockerfile#L1

**Comment by weihao** [comment]
When things aren't working initially then I want to eliminate any unknown risks and then go through all of the variants. 

Where can I learn more about multi-architecture?

**Comment by itzg** [comment]
https://docs.docker.com/docker-for-mac/multi-arch/

https://docs.docker.com/develop/develop-images/build_enhancements/

**Comment by weihao** [comment]
Thank you
